name: Code.json Generator
description: "Automatically generates and updates code.json metadata files for CMS repositories"
author: DSACMS

inputs:
  GITHUB_TOKEN:
    description: "GitHub token used for API access"
    required: true
    default: ${{ github.token }}

outputs:
  updated:
    description: "Boolean indicating whether code.json was updated"
  pr_url:
    description: "URL of the created pull request if changes were made"

runs:
  using: node20
  main: dist/index.js
