name: code.json Auto Generator
description: 'Manages code.json files in repositories, ensuring schema consistency and auto-calculation of certain fields'
author: DSACMS

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
runs:
  using: node20
  main: dist/index.js
