import { CodeJSON } from "./codejson.js";

export const SOFTWARE_TYPES = [
  "standalone/mobile",
  "standalone/iot",
  "standalone/desktop",
  "standalone/web",
  "standalone/backend",
  "standalone/other",
  "addon",
  "library",
  "configurationFiles",
] as const satisfies readonly CodeJSON["softwareType"][];

export const REPOSITORY_TYPES = [
  "package",
  "website",
  "standards",
  "libraries",
  "data",
  "application",
  "tools",
  "APIs",
] as const satisfies readonly CodeJSON["repositoryType"][];

export const PLATFORMS = [
  "mac",
  "web",
  "windows",
  "linux",
  "ios",
  "android",
  "other",
] as const satisfies readonly CodeJSON["platforms"][number][];

// the publiccode.yml controlled vocabulary, mirrored here because the model runs
// offline and cannot read https://publiccodeyml.github.io/v0/categories-list.html
export const CATEGORIES = [
  "accounting",
  "agile-project-management",
  "applicant-tracking",
  "application-development",
  "appointment-scheduling",
  "backup",
  "billing-and-invoicing",
  "blog",
  "budgeting",
  "business-intelligence",
  "business-process-management",
  "cad",
  "call-center-management",
  "cloud-management",
  "collaboration",
  "communications",
  "compliance-management",
  "contact-management",
  "content-management",
  "crm",
  "customer-service-and-support",
  "data-analytics",
  "data-collection",
  "data-visualization",
  "design",
  "design-system",
  "digital-asset-management",
  "digital-citizenship",
  "document-management",
  "donor-management",
  "e-commerce",
  "e-signature",
  "educational-content",
  "email-management",
  "email-marketing",
  "employee-management",
  "enterprise-project-management",
  "enterprise-social-networking",
  "erp",
  "event-management",
  "facility-management",
  "feedback-and-reviews-management",
  "financial-reporting",
  "fleet-management",
  "fundraising",
  "gamification",
  "geographic-information-systems",
  "grant-management",
  "graphic-design",
  "help-desk",
  "hr",
  "ide",
  "identity-management",
  "instant-messaging",
  "integrated-library-system",
  "inventory-management",
  "it-asset-management",
  "it-development",
  "it-management",
  "it-security",
  "it-service-management",
  "knowledge-management",
  "learning-management-system",
  "marketing",
  "mind-mapping",
  "mobile-marketing",
  "mobile-payment",
  "network-management",
  "office",
  "online-booking",
  "online-community",
  "payment-gateway",
  "payroll",
  "predictive-analysis",
  "procurement",
  "productivity-suite",
  "project-collaboration",
  "project-management",
  "property-management",
  "real-estate-management",
  "regulations-and-directives",
  "remote-support",
  "resource-management",
  "sales-management",
  "seo",
  "service-desk",
  "social-media-management",
  "survey",
  "talent-management",
  "task-management",
  "taxes-management",
  "test-management",
  "time-management",
  "time-tracking",
  "translation",
  "video-conferencing",
  "video-editing",
  "visitor-management",
  "voip",
  "warehouse-management",
  "web-collaboration",
  "web-conferencing",
  "website-builder",
  "whistleblowing",
  "workflow-management",
  "other",
] as const;
