name: Update Code.json
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update-code-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update code.json
        id: generator
        uses: DSACMS/automated-codejson-generator@sachin/autoMergeFeat
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_PAT }} 
          BRANCH: "main"
          SKIP_PR: "true"

      - name: Post update information
        run: |
          echo "Update successful: ${{ steps.generator.outputs.updated }}"
          echo "Method used: ${{ steps.generator.outputs.method_used }}"
          if [ "${{ steps.generator.outputs.method_used }}" = "direct_push" ]; then
            echo "✅ Direct push successful! Commit SHA: ${{ steps.generator.outputs.commit_sha }}"
          elif [ "${{ steps.generator.outputs.method_used }}" = "pull_request" ]; then
            echo "📝 Created pull request: ${{ steps.generator.outputs.pr_url }}"
            fi
  
